import Head from "next/head";
import Link from "next/link";
import { Button } from "~/components/ui/button";
import {
  Card,
  CardContent,
  CardDescription,
  CardFooter,
  CardHeader,
  CardTitle,
} from "~/components/ui/card";

export default function Home() {
  const tools = [
    {
      title: "Audio extractor",
      description: "Extract audio from video files",
      url: "/extract-audio",
    },
    {
      title: "Transcriber",
      description: "Transcribe audio or video to text",
      url: "/transcript",
    },
  ];

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col p-4">
        <div>
          <h1 className="text-4xl font-bold text-gray-900">Tools</h1>
          <span>
            A collection of tools to help you with your audio and video files
          </span>
        </div>

        <div className="mt-4 grid grid-cols-3 gap-4">
          {tools.map((tool) => (
            <ToolCard
              key={tool.title}
              title={tool.title}
              description={tool.description}
              url={tool.url}
            />
          ))}
        </div>
      </main>
    </>
  );
}

type ToolCardProps = {
  title: string;
  description: string;
  url: string;
};

function ToolCard({ description, title, url }: ToolCardProps) {
  return (
    <Card>
      <CardHeader>
        <CardTitle>{title}</CardTitle>
        <CardDescription>{description}</CardDescription>
      </CardHeader>

      <CardContent></CardContent>

      <CardFooter className="flex justify-end border-t p-4">
        <Button asChild>
          <Link href={url}>Open</Link>
        </Button>
      </CardFooter>
    </Card>
  );
}
